env:
  DOMAIN: 192.168.39.111.nip.io

  UAA_HOST: uaa.192.168.39.111.nip.io
  UAA_PORT: 2793

kube:
  external_ips: ["192.168.39.111"]

  storage_class:
    persistent: "standard"
    shared: "default"

  registry:
    hostname: "registry.suse.com"
    username: ""
    password: ""
  organization: "cap"
  auth: "rbac"

secrets:
  CLUSTER_ADMIN_PASSWORD: changeme
  UAA_ADMIN_CLIENT_SECRET: changeme

